import type { Metadata } from "next";
import { ArrowUpLeft } from "lucide-react";
import { provenance, sourcePolicy } from "@/lib/data";
import Link from "next/link";
import { DORAR_NOTE } from "@/lib/links";
export const metadata: Metadata = {title: "المصادر"};
export default function Sources() {
  return <main id="main" className="reading-page"><div className="reading-inner"><h1>كل نص، بمرجعه.</h1><p className="reading-lead">فهرس واضح للمواد التي تعتمد عليها المراجعة الحالية. النص القرآني والتفسير محفوظان منفصلين.</p>
    <section className="reading-section"><h2>النص القرآني والسياق</h2><p>مصحف حفص من الموسوعة القرآنية: ١١٤ سورة، و٦٢٣٦ آية، ومنه الآيات المحيطة بالموضع. نسخة البيانات: <bdi>{provenance.version}</bdi>. داخل النتيجة يفتح الرابط الآية نفسها.</p><a className="external-link" href="https://quranpedia.net" target="_blank" rel="noopener noreferrer">الموسوعة القرآنية<ArrowUpLeft size={19} aria-hidden="true" /></a></section>
    <section className="reading-section"><h2>التفسير المتاح</h2><div className="source-table-wrap"><table className="source-table"><thead><tr><th>الكتاب</th><th>المؤلف كما ورد في المصدر</th><th>مواضع الآيات</th></tr></thead><tbody>{provenance.books.map(b => <tr key={b.id}><td>{b.name}</td><td>{b.author}</td><td>{new Intl.NumberFormat("ar-EG").format(b.ayahs)}</td></tr>)}</tbody></table></div><p>يتوفر تفسير في {new Intl.NumberFormat("ar-EG").format(provenance.tafsir_ayahs)} موضعًا مختلفًا في هذين الكتابين. هذا لا يعني تغطية كل الآيات أو تحقيق روايات الكتاب.</p></section>
    <section className="reading-section"><h2>الطبعات وحدود الشرح</h2>{sourcePolicy.tafsir_books.map(b=><div key={b.bookId}><h3>{provenance.books.find(x=>x.id===b.bookId)?.name}</h3><p>{b.edition}</p>{b.attributionNote&&<p>{b.attributionNote}</p>}{b.aiExclusionReason&&<p>{b.aiExclusionReason}</p>}<a className="source-link" href={b.metadataURL} target="_blank" rel="noopener noreferrer">بيانات الكتاب في المصدر</a></div>)}<p>الكتابان من مصادر التفسير في القرون الثلاثة الأولى التي تقبلها المرجعية المعتمدة (مجاهد ت ١٠٤هـ، والثوري ت ١٦١هـ). داخل النتيجة يفتح رابط التفسير صفحة الآية في الكتاب المحدد، مع حفظ الجزء والصفحة لتوثيق النص.</p><p>نعرض التفسير الأصلي المتاح بمصدره، ونوضح غيابه عند نقص البيانات. لا نولّد شرحًا جديدًا، ولا يعد النقل اعتمادًا جديدًا للمادة من اللجنة.</p></section><section className="reading-section"><h2>الدرر السنية</h2><p>{DORAR_NOTE}</p><a className="external-link" href="https://dorar.net/tafseer" target="_blank" rel="noopener noreferrer">الدرر السنية — التفسير<ArrowUpLeft size={19} aria-hidden="true" /></a></section><section className="reading-section"><h2>التوثيق وسلامة النقل</h2><p>تحققنا من بصمات الملفات مقابل سجل المصدر، ومن بقاء نصوص الآيات مطابقة حرفيًا للملفات المحمّلة. أُزيل تنسيق HTML من التفسير لعرضه كنص مقروء؛ روابط كل موضع محفوظة مع بيانات الجزء والصفحة.</p><a className="external-link" href="https://api.quranpedia.net/dumps?lang=ar" target="_blank" rel="noopener noreferrer">ملفات المصدر وإصداراتها<ArrowUpLeft size={19} aria-hidden="true" /></a></section>
    <section className="reading-section"><h2>رخصة البيانات</h2><p>تسمح الموسوعة القرآنية باستعمال هذه البيانات داخل المواقع، مع ذكر المصدر والإصدار عند إعادة نشرها كبيانات قابلة للتنزيل. نحفظ النسبة إلى المصدر ورخصته وسجل الإصدار مع المشروع.</p><a className="external-link" href="https://api.quranpedia.net/dumps/LICENSE.md" target="_blank" rel="noopener noreferrer">رخصة الموسوعة القرآنية<ArrowUpLeft size={19} aria-hidden="true" /></a></section>
    <Link className="reading-cta" href="/">العودة لمراجعة الاقتباس</Link>
  </div></main>;
}
