import {chromium} from 'playwright-core';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const destination=process.env.SIYAQ_QA_DIR||'.qa/free-features';
await mkdir(destination,{recursive:true});
const base=process.env.SIYAQ_QA_URL||'http://127.0.0.1:4183';
const browser=await chromium.launch({executablePath:process.env.SIYAQ_QA_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--disable-gpu']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const errors=[];const uploads=[];const requests=[];
const fixture=await context.newPage();
await fixture.setContent('<html lang="ar" dir="rtl"><body style="margin:0;background:white;padding:70px;font:64px Arial;color:black"><p>لا تقربوا الصلاة</p></body></html>');
await fixture.screenshot({path:`${destination}/ocr-arabic.png`});await fixture.close();
const page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('request',r=>{requests.push({method:r.method(),url:r.url()});if(r.method()==='POST')uploads.push({url:r.url(),body:r.postData()});});
const checks={browser:'Browser plugin not available; isolated Playwright Chrome'};
try{
 await page.goto(base,{waitUntil:'domcontentloaded',timeout:90000});await page.getByRole('heading',{name:/اقرأ الآية/,level:1}).waitFor();
 checks.identity={url:page.url(),title:await page.title()};
 await page.locator('#review').scrollIntoViewIfNeeded();
 await page.screenshot({path:`${destination}/desktop-input.png`});
 await page.locator('input[type=file]').setInputFiles(`${destination}/ocr-arabic.png`);
 await page.waitForFunction(()=>{
  const input=document.querySelector('#quote');
  return input?.value.includes('الصلاة') && !input.disabled;
 },null,{timeout:150000});
 await page.getByText(/استُخرج النص/).waitFor({timeout:10000});
 const text=await page.locator('#quote').inputValue();checks.ocr={text};
 if(!text.includes('الصلاة'))throw Error(`OCR failed to extract Arabic: ${text}`);
 if(uploads.length!==0)throw Error('OCR should not submit any image or text automatically');
 await page.screenshot({path:`${destination}/desktop-ocr.png`});
 await page.getByRole('button',{name:'راجع الاقتباس',exact:true}).click();
 await page.getByTestId('canonical-verse').waitFor({timeout:15000});
 checks.review={text:await page.getByTestId('canonical-verse').innerText()};
 await page.getByRole('tab',{name:'التفسير ومصدره'}).click();
 checks.tafsir=await page.locator('#tafsir-panel').innerText();
 await page.screenshot({path:`${destination}/desktop-result.png`});
 await page.getByRole('button',{name:/العودة للبحث/}).click();
 await page.getByRole('button',{name:'إزالة الصورة',exact:true}).click();
 await page.locator('#quote').fill('الصعوبات يتبعها التيسير');
 await page.getByRole('button',{name:'راجع الاقتباس',exact:true}).click();
 await page.getByRole('heading',{name:'لم نعثر على موضع يمكن تأكيده.'}).waitFor();
 checks.noInventedAnswer=await page.getByTestId('canonical-verse').count()===0;
 await page.screenshot({path:`${destination}/no-match.png`});
 await page.setViewportSize({width:390,height:844});
 await page.goto(base,{waitUntil:'domcontentloaded',timeout:90000});await page.locator('#review').scrollIntoViewIfNeeded();
 await page.screenshot({path:`${destination}/mobile-input.png`});
 checks.mobileNoOverflow=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);
 await page.locator('input[type=file]').setInputFiles({name:'invalid.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});
 await page.getByRole('alert').filter({hasText:'اختر صورة'}).waitFor();
 checks.invalidImage=true;
 checks.noPaidRequests=!requests.some(r=>/api.openai.com|generativelanguage.googleapis.com/.test(r.url));
 checks.noImageUploads=uploads.every(row=>row.url.includes('/api/review'));
 checks.errors=errors;
 if(!checks.mobileNoOverflow||!checks.noPaidRequests||!checks.noImageUploads||!checks.noInventedAnswer||errors.length)throw Error('Browser checks failed');
 console.log(JSON.stringify(checks,null,2));
}catch(e){checks.failure=e.message;await page.screenshot({path:`${destination}/failure.png`}).catch(()=>{});console.log(JSON.stringify(checks,null,2));process.exitCode=1;}
finally{await writeFile(`${destination}/checks.json`,JSON.stringify(checks,null,2));await browser.close();}
